use_frameworks!

target 'JMPagedCollectionLayout_Example' do
  pod 'JMPagedCollectionLayout', :path => '../'

  target 'JMPagedCollectionLayout_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
